/**
 * scripts/download-fonts.mjs
 * Downloads required Google Fonts (.woff2 subsets) locally to public/fonts/
 * and generates src/styles/fonts.css for 100% offline, self-hosted typography.
 */

import fs from 'node:fs';
import path from 'node:path';
import https from 'node:https';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');

const fontsDir = path.join(rootDir, 'public', 'fonts');
const outputCssPath = path.join(rootDir, 'src', 'styles', 'fonts.css');

if (!fs.existsSync(fontsDir)) {
  fs.mkdirSync(fontsDir, { recursive: true });
}

const GOOGLE_FONTS_URL =
  'https://fonts.googleapis.com/css2?family=Tiro+Devanagari+Sanskrit:ital@0;1&family=Martel:wght@400;600;700;800&family=Rozha+One&family=Yantramanav:wght@400;500;700&family=Inter:wght@400;500;600&display=swap';

const USER_AGENT =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36';

function fetchUrl(url, headers = {}) {
  return new Promise((resolve, reject) => {
    https.get(url, { headers }, (res) => {
      if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
        return resolve(fetchUrl(res.headers.location, headers));
      }
      if (res.statusCode !== 200) {
        return reject(new Error(`Failed to fetch ${url}, status: ${res.statusCode}`));
      }
      const chunks = [];
      res.on('data', (chunk) => chunks.push(chunk));
      res.on('end', () => resolve(Buffer.concat(chunks)));
    }).on('error', reject);
  });
}

async function main() {
  console.log('1. Fetching Google Fonts CSS definition...');
  const cssBuffer = await fetchUrl(GOOGLE_FONTS_URL, { 'User-Agent': USER_AGENT });
  const cssText = cssBuffer.toString('utf-8');

  // Match all @font-face blocks
  const fontFaceRegex = /@font-face\s*\{([^}]+)\}/g;
  let match;
  const blocks = [];
  const urlMap = new Map(); // remoteUrl -> localFilename

  while ((match = fontFaceRegex.exec(cssText)) !== null) {
    const blockContent = match[1];
    const urlMatch = blockContent.match(/url\((https:\/\/[^)]+\.woff2)\)/);
    if (urlMatch) {
      const remoteUrl = urlMatch[1];
      if (!urlMap.has(remoteUrl)) {
        // Derive clean local filename: e.g. martel-v14-latin.woff2 or hash
        const parts = remoteUrl.split('/');
        const originalName = parts[parts.length - 1];
        const folderName = parts[parts.length - 2] || 'font';
        const localName = `${folderName}-${originalName}`;
        urlMap.set(remoteUrl, localName);
      }
      blocks.push({
        raw: match[0],
        remoteUrl,
        localName: urlMap.get(remoteUrl),
      });
    }
  }

  console.log(`Found ${urlMap.size} unique font files across ${blocks.length} @font-face rules.`);

  // Download all font files
  console.log('2. Downloading .woff2 font files to public/fonts/...');
  let downloadedCount = 0;
  for (const [remoteUrl, localName] of urlMap.entries()) {
    const localPath = path.join(fontsDir, localName);
    if (!fs.existsSync(localPath)) {
      const fontBuffer = await fetchUrl(remoteUrl, { 'User-Agent': USER_AGENT });
      fs.writeFileSync(localPath, fontBuffer);
      downloadedCount++;
    }
  }
  console.log(`Downloaded ${downloadedCount} new fonts (${urlMap.size} total in public/fonts/).`);

  // Generate self-hosted fonts.css
  console.log('3. Generating src/styles/fonts.css...');
  let localCss = `/* Auto-generated by scripts/download-fonts.mjs — 100% Self-Hosted Offline Fonts */\n\n`;

  let transformedCss = cssText;
  for (const [remoteUrl, localName] of urlMap.entries()) {
    // Note: Gyankosh uses base /gyankosh
    const localUrl = `/gyankosh/fonts/${localName}`;
    transformedCss = transformedCss.replaceAll(remoteUrl, localUrl);
  }

  localCss += transformedCss;
  fs.writeFileSync(outputCssPath, localCss, 'utf-8');
  console.log(`Generated ${outputCssPath} successfully!`);
}

main().catch((err) => {
  console.error('Error downloading fonts:', err);
  process.exit(1);
});
